# Generated by Django 2.0.13 on 2019-04-06 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190406_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 12, 7, 46, 839178, tzinfo=utc)),
        ),
    ]
